### PR TITLE
Feature/aes cbc cts

### PR DESCRIPTION
**Pull request by Kritner**
PR contains specification updates as they relate to the following algorithms:
* ACVP-AES-CBC-CS1
* ACVP-AES-CBC-CS2
* ACVP-AES-CBC-CS3

as defined in https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a-add.pdf

### CODE REVIEW

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Mai 2019, 15:55:07 CEST schrieb Russ Hammett:

Hi Russ,

> PR contains specification updates as they relate to the following
> algorithms: * ACVP-AES-CBC-CS1
> * ACVP-AES-CBC-CS2
> * ACVP-AES-CBC-CS3

In the MCT definition, please clearly indicate:

- what is AES_KEY_SHUFFLE?

- please clarify how the decrypt MCT should work

Ciao
Stephan

**Comment by Kritner** [comment]
The `AES_KEY_SHUFFLE` is defined further down in the document - it's the same as *most* of the other AES algorithms. I believe AES_CFB1 and AES_CFB8 are the only outliers that doesn't use the keyshuffle.

Additionally, there is a note within the spec itself:

```
                    Note: For all the following, the pseudocode for decryption can be obtained by replacing all
                    PT's with CT's and all CT's with PT's. As well, replace the encrypt operation with the corresponding decrypt operation.
```

so the current implementation fits into the existing standard of only defining the encrypt version of the MCT.  If that is insufficient for ACVP-AES-CBC-CS*, it should probably be replaced for all of the MCT algorithms.

Personally, I don't see much use in that, but if enough people feel strongly about the change, it can certainly be done that way.

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Mai 2019, 16:34:49 CEST schrieb Russ Hammett:

Hi Russ,

> The `AES_KEY_SHUFFLE` is defined further down in the document - it's the
> same as *most* of the other AES algorithms. I believe AES_CFB1 and AES_CFB8
> are the only outliers that doesn't use the keyshuffle.
> 
> Additionally, there is a note within the spec itself:
> 
> ```
>                     Note: For all the following, the pseudocode for
> decryption can be obtained by replacing all PT's with CT's and all CT's
> with PT's. As well, replace the encrypt operation with the corresponding
> decrypt operation. ```
> 
> so the current implementation fits into the existing standard of only
> defining the encrypt version of the MCT.  If that is insufficient for
> ACVP-AES-CBC-CS*, it should probably be replaced for all of the MCT
> algorithms.

Ok, I am fine with that since it follows the others.
> 
> Personally, I don't see much use in that, but if enough people feel strongly
> about the change, it can certainly be done that way.

Then please disregard my comments.

Ciao
Stephan

**Comment by Kritner** [comment]
I don't think discarding the comments is the right thing to do - I am curious how others would feel about them, after all it's the others that will be making use of the document.

Oh and I didn't mention it previously, these changes on the server are not yet deployed.  I plan on using the merge of this PR as an indication the algorithm is available to (at a minimum) demo.

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Mai 2019, 15:55:07 CEST schrieb Russ Hammett:

Hi Russ,

> PR contains specification updates as they relate to the following
> algorithms: * ACVP-AES-CBC-CS1
> * ACVP-AES-CBC-CS2
> * ACVP-AES-CBC-CS3
> 
> as defined in
> https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a-a
> dd.pdf You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/usnistgov/ACVP/pull/642

Is it really necessary that we now start down the path of TDES MCT where each 
MCT has its own way of massaging the data?

I was (almost) happy about the AES MCT where all MCTs followed the same 
implementation. Now, with CS MCT, we need:

- to retain CT[i-1]

- to have different handling for inner loop == 0 vs != 0

- print out the key

- shuffle the IV with CT instead with PT.

Can we please define an MCT that is consistent with the rest of the AES MCTs?

The code for TDES MCT is already a nightmare with the different handling for 
each block chain mode with no apparent benefit. Please let us not go down that 
path for AES.

Ciao
Stephan
-- 
atsec information security GmbH, Steinstraße 70, 81667 München, Germany
Phone:     +49 89 442 49 830 - Fax:       +49 89 442 49 831
Mobile DE: +49 172 216 55 78 - Mobile US: +1 512 228 9394
HRB: 129439 (Amtsgericht München)
GF: Salvatore la Pietra, Staffan Persson, Manuela Gambarotto
atsec it security news blog - atsec-information-security.blogspot.com

**Comment by Kritner** [comment]
@smuellerDD I don't think I understand the concern - this is the exact same as the AES-CBC-MCT with the change of using `MSB([value], 128)` rather than just `[value]`.  This MSB was done due to the fact AES-CBC-CS* works on payload lengths greater than the block size.

CBC-MCT:

```
Key[0] = KEY
IV[0] = IV
PT[0] = PT
For i = 0 to 99
    Output Key[i]
    Output IV[i]
    Output PT[0]
    For j = 0 to 999
        If ( j=0 )
            CT[j] = AES_CBC_ENCRYPT(Key[i], IV[i], PT[j])
            PT[j+1] = IV[i]
        Else
            CT[j] = AES_CBC_ENCRYPT(Key[i], PT[j])
            PT[j+1] = CT[j-1]
    Output CT[j]
    AES_KEY_SHUFFLE(Key, CT)
    IV[i+1] = CT[j]
    PT[0] = CT[j-1]
```

CBC-CS* MCT:
```
Key[0] = Key
IV[0] = IV
PT[0] = PT
For i = 0 to 99
    Output Key[i]
    Output IV[i]
    Output PT[0]
    For j = 0 to 999
        If ( j=0 )
            CT[j] = AES_CBC_CS_ENCRYPT(Key[i], IV[i], PT[j])
            PT[j+1] = IV[i] || MSB(CT, PT.length - IV.length)
        Else
            CT[j] = AES_CBC_CS_ENCRYPT(Key[i], PT[j])
            PT[j+1] = CT[j-1]
    Output CT[j]
    AES_KEY_SHUFFLE(Key, CT)
    IV[i+1] = MSB(CT[j], IV.length)
    PT[0] = CT[j-1]
```

The only additional requirement of the CS* MCT is utilizing an MSB function in two additional locations (it is already used within the AES_KEY_SHUFFLE)

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 13:57:23 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I don't think I understand the concern - this is the exact same
> as the AES-CBC-MCT with the change of using `MSB([value], 128)` rather than
> just `[value]`.  This MSB was done due to the fact AES-CBC-CS* works on
> payload lengths greater than the block size.

Sorry for the noise. The error was between desk and chair...

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 14:16:52 CEST schrieb Stephan Mueller:

Hi,

> Am Freitag, 3. Mai 2019, 13:57:23 CEST schrieb Russ Hammett:
> 
> Hi Russ,
> 
> > @smuellerDD I don't think I understand the concern - this is the exact
> > same
> > as the AES-CBC-MCT with the change of using `MSB([value], 128)` rather
> > than
> > just `[value]`.  This MSB was done due to the fact AES-CBC-CS* works on
> > payload lengths greater than the block size.
> 
> Sorry for the noise. The error was between desk and chair...

I would like to air one small issue: The MCT for all other block chaining 
modes contain PT[j+1] = IV for inner loop == 0.

But in some cases, even for the existing block chaining modes, len(PT) > 
len(IV). In this case, PT[j+1] is defined as 00...000|| IV. At least that is 
how I have implemented it. And if I do not pad the IV with the leading zeros, 
the MCT will fail.

The CS MCT requires that the PT[j+1] is IV || CT.
> 
> Ciao
> Stephan



Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 15:11:16 CEST schrieb Stephan Mueller:

Hi,

After looking again, this may be an optimization that I added for CFB1/CFB8. 
Ok, I will shut up now and not add more confusion.

Disregard all questions/issues I had, please.

Ciao
Stephan

**Comment by Kritner** [comment]
:D

**Pull request merged**
