### PR TITLE
V0.5 wip

### PR DESCRIPTION
**Pull request by atvassilev**
Merge this branch into master

### CODE REVIEW

**Comment by celic** [comment]
If we are ready to merge this into master I can resolve the conflicts.

**Comment by atvassilev** [comment]
I have started a PR on this and am resolving the conflicts. Should be ready soon.

**Comment by atvassilev** [comment]
Actually, Chris, something came up and I need to hand this task off to you. I'll abandon my PR, please go ahead, resolve the conflicts and merge. Note that the protocol spec still have explicit references for version number, which are not marked as conflicts. Please be sure to fix them too.

**Comment by atvassilev** [comment]
Abandoning.

**Comment by celic** [comment]
The only references to version I can find are the `docName` which will all be changed into the RFC format later on.

**Pull request closed without merging**
