### PR TITLE
Rsa issue fixes

### PR DESCRIPTION
**Pull request by celic**
A bunch of fixes for RSA issues.

### CODE REVIEW

**Comment by celic** [comment]
This should solve #267

**Comment by celic** [comment]
This is ready for review. The other issues do not require a spec update.

**Comment by celic** [comment]
For 4, there were no changes because the spec was misinterpreted. I do not believe any action is required.

**Comment by atvassilev** [comment]
OK, disregard this comment.

**Comment by atvassilev** [comment]
... and close #262

**Comment by celic** [comment]
I updated the SHA spec to reconcile these changes. This should be how we refer to hash algorithms moving forward. RSA is the first algorithm to need to reference it, but others will come soon and do so in the same manner as RSA.

**Comment by atvassilev** [comment]
Hey, I checked your sha spec changes and it looks like the xml file is updated correctly but the txt artifact is not. Could you double-check on your side, please?

**Comment by celic** [comment]
Whoops, forgot to run the script to generate the files. Uploading them now.

**Comment by celic** [comment]
I can't resolve the conflicts without committing to the merge. They are small conflicts because a commit was accidentally pushed to master instead of the branch. I cannot rollback the commit because master is a protected branch.

**Comment by atvassilev** [comment]
OK, I will merge it as is but please follow up with the artifacts update.

**Comment by celic** [comment]
I just pushed the changes into this branch. I will create a new branch for those changes and delete this branch.

**Pull request merged**
