### PR TITLE
WIP: SP800-38G Revision 1 (draft)

### PR DESCRIPTION
**Pull request by Kritner**
- AES-FF1 and AES-FF3-1.
- Methods for Format Preserving Encryption https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38Gr1-draft.pdf

Plan on using this PR as an area for comments.  The merge of this PR indicates the functionality is now present on (at a minimum) the demo server.

### CODE REVIEW

**Comment by Kritner** [comment]
Note to self as per discussion: update radix max to 64 to support base 64 (alpha numeric +/

**Comment by smuellerDD** [comment]
Am Donnerstag, 20. Juni 2019, 17:48:50 CEST schrieb Russ Hammett:

Hi Russ,

Some comments:

- THe -> The

- Table 7: Alphabet -> alphabet

Ciao
Stephan

**Comment by celic** [comment]
@smuellerDD do you have implementations of this algorithm available in your modules? If so, what radix do you typically see supported? In terms of testing we were looking to support up to base64. In practical applications, I'm not sure I can see a justification for anything beyond that.

**Comment by smuellerDD** [comment]
Am Freitag, 28. Juni 2019, 14:52:11 CEST schrieb Chris Celi:

Hi Chris,

> @smuellerDD do you have implementations of this algorithm available in your
> modules? If so, what radix do you typically see supported? In terms of
> testing we were looking to support up to base64. In practical applications,
> I'm not sure I can see a justification for anything beyond that.

Unfortunately I do not have any IUT as of now. I wanted to implement it myself 
for the Linux kernel, but then got side-tracked to do other work.

Ciao
Stephan

**Comment by celic** [comment]
No problem. It'll stand as an open question for those looking at this PR.

**Comment by Kritner** [comment]
AES-FF1 and AES-FF3-1 are now on demo.  This algorithm will (for now) not be present on production as the specification is still in draft.  Merging in this PR as it is on demo.

**Comment by celic** [comment]
As a heads up, when we add a new algorithm to the demo environment that wasn't previously tested by CAVS, we will hold it on demo for an extended period of time to ensure everything runs smoothly before moving it along to prod.

**Pull request merged**
