### PR TITLE
Adds "revision" to Symmetric spec

### PR DESCRIPTION
**Pull request by celic**
Also updates examples so there are no extremely long strings. This is a requirement for IETF publications.

### CODE REVIEW

**Comment by celic** [comment]
Also fixes #543

**Comment by acronymhaterheidi** [comment]
This replaces `payloadLen` with `dataLen` in some of the tables but nowhere else. Is this a new key for some of the block cipher modes?

**Comment by celic** [comment]
Thank you for the heads up. This is unintentional as I pasted my tables from an excel sheet. The excel sheet wasn't updated with the proper names for those properties. I'll update this PR.

**Comment by celic** [comment]
I've got some final updates for this coming today.

**Pull request merged**
