### PR TITLE
KAS KDF Additional KdfConfig/KdfParam information around `l`

### PR DESCRIPTION
**Pull request by Kritner**
* https://github.com/usnistgov/ACVP/issues/1048

### CODE REVIEW

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. November 2020, 17:12:07 CET schrieb Russ Hammett:

Hi Russ,

> * https://github.com/usnistgov/ACVP/issues/1048
> You can view, comment on, or merge this pull request online at:

Is the change really true? What I have seen is that l is treated as a byte 
value...

Ciao
Stephan

**Comment by Kritner** [comment]
> Is the change really true? What I have seen is that l is treated as a byte value...

it's *going to be* true.  It was always intended to be bit like the other kas KDFs, just a mistake on implementation.

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. November 2020, 17:47:30 CET schrieb Russ Hammett:

Hi Russ,

> > Is the change really true? What I have seen is that l is treated as a byte
> > value...
> it's *going to be* true.  It was always intended to be bit like the other
> kas KDFs, just a mistake on implementation.

Ah, sorry, I was missing that last point that you intend to change it :-)

Disregard my question and I am waiting for your update.

Ciao
Stephan

**Comment by Kritner** [comment]
Yeah sorry, that's related to the comments in https://github.com/usnistgov/ACVP/issues/1048#issuecomment-721820112.  I'll keep this PR open and merge it in once the change from "byte" to "bit" makes to to (at a minimum) demo.

**Pull request merged**
