### PR TITLE
Addition of Query Parameters to specification

### PR DESCRIPTION
**Pull request by hbooth**

### CODE REVIEW

**Comment by smuellerDD** [comment]
Am Montag, 13. Mai 2019, 15:57:34 CEST schrieb Harold Booth:

Hi Harold,

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/usnistgov/ACVP/pull/646
> 
> -- Commit Summary --
> 
>   * initial description of query parameters
>   * added an example
>   * added an example to attempt a better explaination at what group index
> means * updated to include description of available query parameters for
> each resource

Can you please add information on how to handle non-US-ASCII characters? A 
reference to RFC3986 only helps with the encoding approach, but does not give 
an information about what to encode.

Example: see my last name "Müller". Now, how shall that be written?

- ASCII: M%DCller

- UTF-8: M%C3%BCller

Ciao
Stephan

**Comment by hbooth** [comment]
I thought RFC3986 recommended UTF-8. I pretty much only tested with UTF-8 encoding. Would it be fine to just require UTF-8 when specifying RFC3986?

**Comment by smuellerDD** [comment]
Am Montag, 13. Mai 2019, 16:34:01 CEST schrieb Harold Booth:

Hi Harold,

> I thought RFC3986 recommended UTF-8. I pretty much only tested with UTF-8
> encoding. Would it be fine to just require UTF-8 when specifying RFC3986?

When read the RFC, an UTF-8 requirement seems to be only present for the host 
encoding. For all others, it is a recommendation only.

Ciao
Stephan

**Comment by hbooth** [comment]
I am not 100% sure what needs to be added.

What would you like to see put into the specification?

Would:
```
The URL including the parameter values MUST conform to RFC3986 and MUST use UTF-8 character encoding.
```
work?

Any suggestions on how to better document this would be welcome.

**Comment by smuellerDD** [comment]
Am Montag, 13. Mai 2019, 16:44:06 CEST schrieb Harold Booth:

Hi Harold,

> The URL including the parameter values MUST conform to RFC3986 and MUST use
> UTF-8 character encoding. ```
> work?

Perfect, that would be great.


Ciao
Stephan

**Pull request merged**
