### PR TITLE
KAS-KDF HKDF SP800-56Cr1 specification

### LINKED ISSUE #954: Introduce specification for KAS-KDF / HKDF / Sp800-56Cr1
HKDF is a subset of TwoStep kdf, however can be validated independently of it, and has a much simpler registration than the TwoStep KDF

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr1.pdf

Introduce specification for this new algorithm.

### PR DESCRIPTION
**Pull request by Kritner**
- closes #954

### CODE REVIEW

**Comment by smuellerDD** [comment]
Am Dienstag, 18. August 2020, 18:20:49 CEST schrieb Russ Hammett:

Hi Russ,

> - closes #954
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/usnistgov/ACVP/pull/957
> 
> -- Commit Summary --
> 
>   * KAS-KDF HKDF SP800-56Cr1 specification
> 
> -- File Changes --
> 
>     M README.md (1)
>     A src/draft-hammett-acvp-kas-kdf-hkdf.adoc (48)
>     A src/kas/sp800-56cr1/hkdf/sections/03-supported.adoc (7)
>     A src/kas/sp800-56cr1/hkdf/sections/04-testtypes.adoc (25)
>     A src/kas/sp800-56cr1/hkdf/sections/05-capabilities.adoc (137)
>     A src/kas/sp800-56cr1/hkdf/sections/06-test-vectors.adoc (322)
>     A src/kas/sp800-56cr1/hkdf/sections/07-responses.adoc (103)
>     A src/kas/sp800-56cr1/hkdf/sections/98-references.adoc (155)

Comments:

- prerequisites: only HMAC SHA2 or SHA3 are supported - why are there so many 
other prereqs defined (CMAC, KMAC, ...)?

- why is it mandatory to have uPartyInfo and vPartyInfo (note, the ACVP server 
rejected requests without them)?

> 
> -- Patch Links --
> 
> https://github.com/usnistgov/ACVP/pull/957.patch
> https://github.com/usnistgov/ACVP/pull/957.diff


Ciao
Stephan

**Comment by Kritner** [comment]
> prerequisites: only HMAC SHA2 or SHA3 are supported - why are there so many other prereqs defined (CMAC, KMAC, ...)?

That was just a mistake, I'll put in a correction.

> why is it mandatory to have uPartyInfo and vPartyInfo (note, the ACVP server rejected requests without them)?

Perhaps it shouldn't be required like it currently is, but my initial reactions were to do so for testing purposes against the ACVP server.  The entire premise of the `fixedInfo` field is to have contextually bound data go into this field per key exchange; this seems to be a method to ensure it, at least for testing purposes.  

The `[x]PartyInfo` field is (sometimes) made up of multiple fields which can vary on the KAS scheme tested.  This KDF specific testing is completely separate from any one KAS "flavor" and/or scheme; I wanted to make sure that test cases were produced that would randomly have (or not) `ephemeralData` to plug in, in addition to the always provided `partyId`.

All that being said, this is in the demo environment for just these sorts of questions. It doesn't have to be this exact method of testing by the time it goes to prod.  Hopefully the above makes sense as to *why* I went the route I did for this KDF testing, I am open to hearing further suggestions and/or modifications to the current testing.  Ideally the testing would be non specific to a KAS scheme while being able to exercise testing against some of the variations between the KAS schemes.

**Comment by Kritner** [comment]
@smuellerDD I'm going to open back up the issue #957 for the specification and put my reply there as well.  It might be easier to keep track of our dialog in issue form

**Comment by smuellerDD** [comment]
Am Mittwoch, 19. August 2020, 11:37:46 CEST schrieb Russ Hammett:

Hi Russ,

If the test is not yet in flux, may I ask to consider the following: HKDF is 
in the same league as SP800-108 KDF. It is used in scenarios other than solely 
in a SP800-56A scenario. For example, the Linux kernel uses HKDF for file-
based encryption to derive per-file keys from one given master secret.

That said, looking at just HKDF, I think there should be no limitation from 
protocols like SP800-56A. SP800-56C does not seem to limit the input data to 
HKDF to the structure of [x]PartyInfo or similar in chapter 5 which defines 
KDFs like HKDF.

With that in mind, may I propose that the HKDF testing is modified to resemble 
more the SP800-108 testing including the cipher requests and the test vectors?

As SP800-108 and HKDF are specific option for the two-step KDF in scenarios 
involving SP800-56A, their "protocol-specific" input with the [x]PartyInfo can 
be considered in such a case.

Ciao
Stephan

**Comment by Kritner** [comment]
This particular group of testing ***is*** specifically for use as a KAS KDF.  HKDF is not currently an approved NIST standalone algorithm so testing has not yet been released for it.  

If we *were* to release HKDF standalone testing, currently it would only be for demo due to the above.

**Comment by smuellerDD** [comment]
Am Mittwoch, 19. August 2020, 17:58:20 CEST schrieb Russ Hammett:

Hi Russ,

> This particular group of testing ***is*** specifically for use as a KAS KDF.
>  HKDF is not currently an approved NIST standalone algorithm so testing has
> not yet been released for it.

I see, please disregard my comment then.
> 
> If we *were* to release HKDF standalone testing, currently it would only be
> for demo due to the above.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 19. August 2020, 18:01:35 CEST schrieb Stephan Mueller:

Hi,

> Am Mittwoch, 19. August 2020, 17:58:20 CEST schrieb Russ Hammett:
> 
> Hi Russ,
> 
> > This particular group of testing ***is*** specifically for use as a KAS
> > KDF.> 
> >  HKDF is not currently an approved NIST standalone algorithm so testing
> >  has
> > 
> > not yet been released for it.
> 
> I see, please disregard my comment then.

Allow me to re-open this issue: SP800-56C revision *2* just came out. Chapter 
5 does NOT seem to include the link between twostep KDFs and SP800-56A any 
more!

With that, it seems HKDF testing should be more like SP800-108 testing unless 
I miss something.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Do you happen to have a hint on what we can tell customers who use HKDF as a general-purpose KDF?

**Comment by hallnist** [comment]
Hi Stephan,

I recommend that you contact the NIST CT group about approving HKDF as a general-purpose KDF.  Lily Chen is the group leader, author of SP 800-108 and one of the authors of SP 800-56C Rev 1/2.

**Comment by smuellerDD** [comment]
Am Montag, 24. August 2020, 15:34:49 CEST schrieb hallnist:

Hi hallnist,

> Hi Stephan,
> 
> I recommend that you contact the NIST CT group about approving HKDF as a
> general-purpose KDF.  Lily Chen is the group leader, author of SP 800-108
> and one of the authors of SP 800-56C Rev 1/2.

What I am saying is that 56C revision 2 DOES (seem) to define a general 
purpose HKDF now. I.e. there is NO binding to 56A any more. If I am correct, 
the CT group now DID mark HKDF suitable for general purpose use.

That said, I am wondering whether a general-purpose HKDF ACVP test is in the 
pipeline.

Ciao
Stephan

**Comment by hallnist** [comment]
Hi Stephan,

This is Tim Hall.  I am happy to follow up with the Lily et al. on this in case we have missed something.  I understood the "Z" input (whether the 'standard' Z or the new hybrid Z' = Z || T defined in 56Cr2) to be the following throughout SP 800-56Cr2:

(From Section 2, "Scope and Purpose") "This Recommendation specifies two categories of key-derivation methods that can be employed, as required, to derive keying material from a shared secret Z generated during the execution of a key-establishment scheme specified in [SP 800-56A] or [SP 800-56B]."

I will follow up with Lily et al. anyway, to make sure we follow their intentions, but if I have missed something in the SP that indicates HKDF should be a more general-purpose KDF, let me know.

**Comment by smuellerDD** [comment]
Am Montag, 24. August 2020, 16:38:27 CEST schrieb hallnist:

Hi Tim,

Thanks for your answer. My question comes from the removal of the 56A 
references in chapter 5 - compare both chapters from 56C rev 1 and rev 2.

I see that binding 56A in chapter 2 of 56C rev 2 as you hinted. Also in the 
intro to 56C rev 2 the binding to 56A is made. But the explicit removal of the 
56A reference from chapter 5 raises the question by others whether HKDF is now 
considered a general-purpose KDF.

Would it be possible that you drop Lily a note just asking whether HKDF is now 
a general-purpose KDF with 56C rev 2 or not considering that the specific 
reference to 56A in chapter 5 is removed? The issue is that many folks use 
HKDF due to its nice properties of "seeding" it once and obtaining data during 
several independent requests. I.e. the expand step can be invoked multiple 
times, i.e. making it behave like a deterministic RNG.

Thanks a lot.

Ciao
Stephan

**Comment by hallnist** [comment]
Hi Stephan,

Yes, that text was removed from Section 5 (which applies to all two-step KDFs, not just HKDF), but it was also removed from the text of Section 4 (all one-step KDFs).  So if the removal of that text was intended to drop the binding to 56A and 56B, that would apply to *all* one-step and two-step KDFs in 56Cr2, which I am certain is not the intention.  It is pretty clear to me that 56Cr2 defines approved KDFs for use in a 56A or 56B key establishment scheme, as indicated in the title, intro, scope and purpose, etc.

Having said that, it is possible that the CT group intends to approve HKDF for other uses, either now or in the future.  I have seen some indications that they might intend that (at least at some point).  I just don't think that the text changes in 56Cr2 are an indication of that.  I will check with Lily et al.  Thanks,

Tim

**Comment by hallnist** [comment]
I sent an email about it.  Will let you know. -- Tim

**Comment by hallnist** [comment]
Hi again,

I talked with Lily and the CT group about this.  Two things:

1. We all agree that SP 800-56C Rev2 applies only to KDFs that are part of an approved key agreement scheme, i.e. those in SP 800-56Ar3 and SP 800-56Br2.

2. SP 800-133 Rev 2, Sec. 6.3, Step 3 has a key extraction process that maps to HKDF-Extract.  The input key(s) and other data are concatenated together in the "IKM" input to HKDF-Extract.  The resulting key can then be used as the "PRK" input to HKDF-Expand.  Of course, the input to the key extraction process must meet the requirements in SP 800-133 Rev 2; it cannot be just anything.  For example, for the Linux kernel example you gave, the master secret must be a key or output of an approved key generation method, i.e., one that meets the requirements of SP 800-133 Rev 2.

Tim

**Comment by smuellerDD** [comment]
Am Donnerstag, 27. August 2020, 15:41:29 CEST schrieb hallnist:

Hi hallnist,

> Hi again,
> 
> I talked with Lily and the CT group about this.  Two things:

Thanks a lot for your followup!

> 
> 1. We all agree that SP 800-56C Rev2 applies only to KDFs that are part of
> an approved key agreement scheme, i.e. those in SP 800-56Ar3 and SP
> 800-56Br2.

That is now clear and no further questioned. Thank you.
> 
> 2. SP 800-133 Rev 2, Sec. 6.3, Step 3 has a key extraction process that maps
> to HKDF-Extract.  The input key(s) and other data are concatenated together
> in the "IKM" input to HKDF-Extract.  The resulting key can then be used as
> the "PRK" input to HKDF-Expand.  Of course, the input to the key extraction
> process must meet the requirements in SP 800-133 Rev 2; it cannot be just
> anything.  For example, for the Linux kernel example you gave, the master
> secret must be a key or output of an approved key generation method, i.e.,
> one that meets the requirements of SP 800-133 Rev 2.

When I read 6.3, I interpret that not only approved key *generation* but also 
approved key establishment methods (see first sentence in section 6.3: " ... 
are generated and/or established independently ..."). And with establishment 
method, I refer to the terminology of D.2. Please help me whether I am 
mistaken here.

Considering this statement and assuming that an approved key generation or 
establishment method is used, HKDF seems to be usable and allowed.

Now coming back to the original question: could you fathom defining a general 
purpose HKDF test and thus approve HKDF usable compliant to either 56Arev 3 / 
56B rev 3 or 133 rev 2?

Thanks a lot for your help.

Ciao
Stephan

**Comment by hallnist** [comment]
Hi Stephan,

Thanks.  I gave two cases, "key" or "output of an approved key generation method."  "key" in my usage above includes establishment per 6.3.  I phrased the second case "output of ..." as such because you described the input in the Linux kernel use case as a "master secret" and not a "key."  The important thing is that this input key/master secret conform to SP 800-133 Rev 2, Sec 3, which references other sections in the SP for requirements on it.  For example, see footnote 27, which cites Sec 4, 6.1 and 6.2.

We will consider how best to support the SP 800-133 Rev2 extraction + expansion step.  I hesitate to call it a "general purpose" HKDF though.

Best regards,

Tim

**Comment by smuellerDD** [comment]
Am Donnerstag, 27. August 2020, 16:43:00 CEST schrieb hallnist:

Hi hallnist,

> Hi Stephan,
> 
> Thanks.  I gave two cases, "key" or "output of an approved key generation
> method."  "key" in my usage above includes establishment per 6.3.  I
> phrased the second case "output of ..." as such because you described the
> input in the Linux kernel use case as a "master secret" and not a "key." 
> The important thing is that this input key/master secret conform to SP
> 800-133 Rev 2, Sec 3, which references other sections in the SP for
> requirements on it.  For example, see footnote 27, which cites Sec 4, 6.1
> and 6.2.

Brilliant - that would be exactly what a lot of folks do.
> 
> We will consider how best to support the SP 800-133 Rev2 extraction +
> expansion step.

That would be most awesome.

> I hesitate to call it a "general purpose" HKDF though.

Sure, we will follow you lead and call it how you designate it. The key for us 
is that it allows sections 4, 6.1, 6.2 and all key establishment methods as 
input into the HKDF.


Thanks a lot for your considerations.

Ciao
Stephan

**Pull request merged**
