### PR TITLE
Symmetric spec `dataLen`, `ptLen`, `ctLen` -> `payloadLen`

### PR DESCRIPTION
**Pull request by Kritner**
Updates symmetric spec to use `payloadLen` as the property name, taking place of `ptLen`, `ctLen`, and `dataLen`

What is everyone's thoughts on this? I know we're kind of late in the v0.5 game here, but right now the spec isn't matching the server, and `dataLen` can be somewhat ambiguous (IMO).

### CODE REVIEW

**Comment by Kritner** [comment]
Note this is not done yet, i just wanted to get something out there for visibility, i have a few more commits to make

**Comment by Kritner** [comment]
Note - these changes are now completed, and will be deployed to the demo server in the next release.  I will merge this PR into master at that point.

**Comment by Kritner** [comment]
This will close #469 once merged in

**Comment by smuellerDD** [comment]
confirmed, working

**Pull request merged**
