### PR TITLE
PR - updates to artifacts, new windows batch file to generate artifacts on windows

### PR DESCRIPTION
**Pull request by Kritner**
- Created `WindowsGenerateArtifacts.bat` for use in recreating `artifacts` from `src` in a Windows environment.
- Updated all `artifacts` from `src`
- Updated `README.md` with basic instructions for keepings `artifacts` an `src` synchronized.

### CODE REVIEW

**Comment by Kritner** [comment]
Looks like there are some issues in the artifacts that would conflict due to the other pull request.  Can probably resolve this by recreating the artifacts from the XML.  I can try to do that today.

**Comment by atvassilev** [comment]
Just to double-check: earlier today I merged #7. If this pull request gets merged, it would not invalidate the updates from #7 in src but the artifacts will not be current since you generated them from the previous version of acvp_protocol.xml, correct?

**Comment by Kritner** [comment]
@atvassilev in commit fc7f93f48774bbbea17300f98865636db255214e I regenerated the protocol artifacts  based on the new .xml file from #17.  This can be confirmed by searching "sub-document" as that was a typo corrected, as well as the new section "Vector Set Expiration".  My changes do not take into account 719987b63d2bb193ca1218d520a1d2a644d7e70d. I can update that now.

**Comment by Kritner** [comment]
Updated artifacts with changes from 719987b63d2bb193ca1218d520a1d2a644d7e70d

**Pull request merged**
