### PR TITLE
Adds LMS

### PR DESCRIPTION
**Pull request by celic**

### CODE REVIEW

**Review by Kritner — CHANGES_REQUESTED** [review]
Will probably want to add pseudocode for the deterministic keygen/signatures aspects of the algorithm.

I think there was (perhaps) a deterministic method specified in either the RFC or SP around key generation.  But (unless it was removed) there is also a deterministic method for `c` generation for the creation of signatures?

I may be misremembering some things here, but wanted to at least call it out!

**Comment by livebe01** [comment]
The LMS modes are camel case in some parts of the spec and pascal case in others. Do you want them to be camel case like RSA or something else?

**Review by livebe01 — COMMENTED** [review]
Apart from the question/comment I made about mode casing, looks good!

**Comment by celic** [comment]
Will update casing to be consistent with other signature algorithms. Will add discussion on deterministic tree/signature generation.

**Comment by celic** [comment]
Please double check the casing to see if I missed anything. Also added a note in the `Requirements Covered` section on the pseudorandom LMOTS key generation. It's added as a *MAY* but it is how the NIST ACVTS instance will test LMS keyGen. I did not add discussion on pseudorandom `C` because it is not relevant for LMS. It will be relevant for HSS though.

**Review by Kritner — APPROVED** [review]

**Comment by livebe01** [comment]
> 

@celic, can you double check that the doc still builds locally for you? It built fine for me yesterday morning, but errors out now w/ the latest changes.

**Comment by celic** [comment]
Everything builds just fine on GitHub Actions

**Comment by celic** [comment]
Messed up an RFC reference. Fixed.

**Comment by livebe01** [comment]
Looks good to merge to me.

**Comment by celic** [comment]
Please merge when LMS goes to Demo.

**Pull request merged**
