### PR TITLE
Change outLength to domain in SHAKE registration example

### PR DESCRIPTION
**Pull request by acronymhaterheidi**
Fixes error pointed out in #545

### CODE REVIEW

**Comment by celic** [comment]
This does not contain the compiled artifacts (txt, html) but does fix the issue in the xml. (The compiled artifacts arguably don't belong in the repository at all). I'm fine approving this and merging it in and adding the artifacts later. Thoughts @atvassilev ?

**Comment by bfussell** [comment]
I guess the other 2 files, .txt and .html, need updating as well ?

**Comment by celic** [comment]
I incorporated this change into #551 and included the compiled artifacts.

**Comment by celic** [comment]
Reopening because the other PR #551 is not being merged at the moment. This should be merged to fix the listed issue. Sorry for the confusion.

**Comment by celic** [comment]
I will merge this and follow up with the compiled artifacts.

**Pull request merged**
