### PR TITLE
Fixes for various SPEC issues

### PR DESCRIPTION
**Pull request by smuellerDD**
Each fix in the following list addresses one reported issue.

### CODE REVIEW

**Comment by celic** [comment]
Awesome! I guess we have a lot of issues to close out now. Thank you for contributing @smuellerDD

**Comment by atvassilev** [comment]
Stephan, 

I just merged your pull request into the master. FYI, we expect people to supply also the artifacts in txt and html format with each PR but since this is your first PR on this, you may not be aware of this policy. Could you please generate the txt and html versions and commit to artifacts? You could use this tool https://xml2rfc.tools.ietf.org/ if you don't have one already. Let me know if you have any questions.

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Juli 2018, 17:16:14 CEST schrieb Apostol Vassilev:

Hi Apostol,

> Stephan,
> 
> I just merged your pull request into the master. FYI, we expect people to
> supply also the artifacts in txt and html format with each PR but since
> this is your first PR on this, you may not be aware of this policy. Could
> you please generate the txt and html versions and commit to artifacts? You
> could use this tool https://xml2rfc.tools.ietf.org/ if you don't have one
> already. Let me know if you have any questions.

I did not know that. Thanks for the reminder. Let me generate those.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Juli 2018, 17:16:14 CEST schrieb Apostol Vassilev:

Hi Apostol,

> Stephan,
> 
> I just merged your pull request into the master. FYI, we expect people to
> supply also the artifacts in txt and html format with each PR but since
> this is your first PR on this, you may not be aware of this policy. Could
> you please generate the txt and html versions and commit to artifacts? You
> could use this tool https://xml2rfc.tools.ietf.org/ if you don't have one
> already. Let me know if you have any questions.

Artifacts pushed to my Github fork.

Ciao
Stephan

**Comment by atvassilev** [comment]
Thanks for the quick turnaround. I don't see it though, did you sync with the remote repo?

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Juli 2018, 18:48:11 CEST schrieb Apostol Vassilev:

Hi Apostol,

> Thanks for the quick turnaround. I don't see it though, did you sync with
> the remote repo?

Sorry, I initially pushed the master and not the branch. It is there now.

Ciao
Stephan

**Comment by atvassilev** [comment]
Hmm, I am still puzzled. Could you please provide your branch explicitly?

**Pull request merged**
