### PR TITLE
Clarify uniqueness requirement for test case ID. Eliminate overloaded…

### PR DESCRIPTION
**Pull request by jfigus**
This addresses issues #13 and #14.  If this change looks good and is accepted, I can update all the other sub-specs to use this new verbiage.

### CODE REVIEW

**Comment by Kritner** [comment]
If at all possible, could #16 be merged prior to #18?  This PR does not contain updates to artifacts as the comment indicates (at least as of this comment), and #16 has updates to all artifacts.  If this PR (#18) is merged first, #16 will likely get merge conflicts again.

**Comment by jfigus** [comment]
That's fine with me.  In the future, I'm thinking we should only take pull requests for the source files.  Then the artifacts would be regenerated and committed periodically to the repo by one of the repo owners.

**Comment by atvassilev** [comment]
This would be fine with me.

**Comment by jfigus** [comment]
OK, I'll submit another PR with the same change to the other sub-specs.

**Pull request merged**
