### PR TITLE
Updated DRBG to show support for SHA3.

### PR DESCRIPTION
**Pull request by jbrock24**

### CODE REVIEW

**Comment by livebe01** [comment]
This section should be updated as well: https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html#name-supported-values-per-drbg-o

**Comment by jbrock24** [comment]
I think that's the only thing I changed, did you mean somewhere else? 

[src/drbg/sections/05-capabilities.adoc](https://github.com/usnistgov/ACVP/blob/b699ad27903d5a89b247691637f8d886a91c4284/src/drbg/sections/05-capabilities.adoc?plain=1#L56-L96)

**Comment by jvdsn** [comment]
Is there any reference for SHA-3 DRBGs being FIPS approved? Or is this only added to ACVP to show support (similar to AES-GCM-SIV)?

**Comment by jbrock24** [comment]
Hi @jvdsn, yes it's approved in a future version of 90A, they are good to use now, just takes a while to get the standard updated.

**Pull request merged**
